name: Create and publish docker iamge 

on: 
  workflow_dispatch 

env: 
  REGISTRY: ghrc.io
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  build-and-push-image:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write

    steps: 
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login 
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract
        id: meta 
        uses: docker/metadata-action@v3
        with: 
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push 
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with: 
          context: .
          push: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


